title: Presentations
description: Presentations
baseurl: "/presentations"
url: "https://tisnik.github.io"

heading_anchors: true
search_enabled: false

aux_links:
  "Github repository":
    - "https://github.com/tisnik/presentations"

footer_content: "Copyright &copy; 2019, 2020, 2021, 2022 Pavel Tisnovsky"

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

theme: jekyll-theme-leap-day
